sudo: required
language: generic
dist: bionic

os:
  - linux
  - osx

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
    - TRAVIS_BUILD_TYPE=Release
    - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
    - TRAVIS_TEST_TARGET="test"
    - TRAVIS_INSTALL_TARGET="install"

matrix:
  include:
    - os: osx
      env: TRAVIS_CMAKE_GENERATOR="Xcode"

branches:
  except:
  - gh-pages
  - appveyor

before_script:
  - if [ "${TRAVIS_CMAKE_GENERATOR}" = "Xcode" ]; then export TRAVIS_TEST_TARGET="RUN_TESTS"; fi
  - cmake -H. -Bbuild -G"${TRAVIS_CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=$(pwd)/../install -DYCM_MAINTAINER_MODE=ON

script:
  - cmake --build build --config ${TRAVIS_BUILD_TYPE}
  - cmake --build build --config ${TRAVIS_BUILD_TYPE} --target ${TRAVIS_TEST_TARGET}
  - cmake --build build --config ${TRAVIS_BUILD_TYPE} --target ${TRAVIS_INSTALL_TARGET}
