name: 'Generate GH Pages'

on:
  push:
    branches:
      - master
      - devel

jobs:
  generate-gh-pages:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Generate GH Pages
      uses: ./.github/actions/generate-gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
