name: 'Generate GH Pages'

on:
  push:
    branches:
      - master
      - devel

jobs:
  generate-gh-pages:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Generate GH Pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: generated_docs
        BUILD_SCRIPT: apt-get install -y cmake python3-sphinx && tools/gen-gh-pages.sh && git reset --hard gh-pages && git reset origin/master && mkdir generated_docs && mv gh-pages/ index.html generated_docs
