name: 'Nightly Merge'

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  nightly-merge-ycm-0-12:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.3.0
      with:
        stable_branch: 'ycm-0.12'
        development_branch: 'master'
        allow_ff: false
        user_name: 'Daniele E. Domenichelli (Nightly Merge Action)'
        user_email: 'daniele.domenichelli@iit.it'
        push_token: 'drdanz_TOKEN'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        drdanz_TOKEN: ${{ secrets.drdanz_TOKEN }}

  nightly-merge-ycm-devel:
    runs-on: ubuntu-latest
    needs: nightly-merge-ycm-0-12
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.3.0
      with:
        stable_branch: 'master'
        development_branch: 'devel'
        allow_ff: true
        ff_only: true
        user_name: 'Daniele E. Domenichelli (Nightly Merge Action)'
        user_email: 'daniele.domenichelli@iit.it'
        push_token: 'drdanz_TOKEN'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        drdanz_TOKEN: ${{ secrets.drdanz_TOKEN }}
